### ISSUE TITLE
Monero Wallet RPC (Wrong parsing?)

### ISSUE THREAD

**Issue by yovanoc** [vMReal/digest-auth#8]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I try to made a got plugin with your lib to contact the monero wallet rpc (https://web.getmonero.org/resources/developer-guides/wallet-rpc.html)

My code:

```ts
import got from "got";
import { ClientDigestAuth } from "@mreal/digest-auth";

export function createDigestClient(username: string, password: string) {
  return got.extend({
    hooks: {
      afterResponse: [
        (res, retry) => {
          const options = res.request.options;
          const digestHeader = res.headers["www-authenticate"];

          if (!digestHeader) {
            return res;
          }

          const incomingDigest = ClientDigestAuth.analyze(digestHeader);

          console.log(incomingDigest);

          const digest = ClientDigestAuth.generateProtectionAuth(
            incomingDigest,
            username,
            password,
            {
              method: options.method,
              uri: options.url.pathname,
              counter: 1
            }
          );

          options.headers.authorization = digest.raw;

          return retry(options);
        }
      ],
      beforeRetry: [
        (options, error, retryCount) => {
          console.log(options.headers, error, retryCount);
        }
      ]
    }
  });
}
```

* **Other information**

The `console.log(incomingDigest)` in the middle give me that `{ qop: '"auth",algorithm' }` so I think there is a problem.. I get a 401 with this response back

`authorization: 'Digest username="devchris", response="db6ef15a168d8bf094b052af5804c9b6", cnonce="c3c5ecd9941663e3c13f1dd890cf2d6b8f7ee865acedd98e", nc=00000001, uri="/json_rpc", qop=auth, algorithm="MD5"'`

**Comment by vMReal** [comment]
Thanks for reporting the problem. I am trying to resolve the problem asap.

**Comment by vMReal** [comment]
Could you provide the first response from the server (before console.log(incomingDigest) ). It will help a lot.

**Comment by yovanoc** [comment]
Ahah of course, here it is:

`Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="RfLCEIHjDR7DgKXvotSMMg==",stale=false, Digest qop="auth",algorithm=MD5-sess,realm="monero-rpc",nonce="RfLCEIHjDR7DgKXvotSMMg==",stale=false`

**Comment by vMReal** [comment]
The Problem was fixed https://github.com/vMReal/digest-auth/releases/tag/v1.1.0

Monero wallet rpc return "Multiple Authorization Header" (2 digest in one header) (This is strange because it is a duplicate). But the standard allows you to do this.

Before, this module not supported "Multiple Authorization Header" as result you have such behavior.

The release v1.1.0 fixed this issue by adding support "Multiple Authorization Header". Additional information has been added. README.md

**For resolve, your case need update module to the latest version without any changes in code**

**Comment by vMReal** [comment]
The Problem was fixed https://github.com/vMReal/digest-auth/releases/tag/v1.1.0

**Comment by yovanoc** [comment]
I still receive a 401 from the monero wallet, but with curl is working, how have you test that?

![image](https://user-images.githubusercontent.com/7302317/73274560-0deada00-41e6-11ea-9560-165007bf6c5a.png)

**Comment by vMReal** [comment]
Still have problems with parse

**Comment by vMReal** [comment]
I have added fix. https://github.com/vMReal/digest-auth/releases/tag/1.1.1

Please try again, and send me any information

**Comment by yovanoc** [comment]
Still doesn't work. I tried to read the digest auth rfc but I can't see what are you doing wrong here...

![image](https://user-images.githubusercontent.com/7302317/73307165-f9c2cf00-421d-11ea-922e-0c2d14c657b3.png)

**Comment by vMReal** [comment]
I did some research on real services

```
function createDigestClient(username, password) {
    return got.extend({
      hooks: {
        afterResponse: [
          (res, retry) => {
            const options = res.request.options;
            const digestHeader = res.headers["www-authenticate"];

            if (!digestHeader) {
              return res;
            }

            const incomingDigest = ClientDigestAuth.analyze(digestHeader);

            console.log(incomingDigest);

            const digest = ClientDigestAuth.generateProtectionAuth(
              incomingDigest,
              username,
              password,
              {
                method: options.method,
                uri: options.url.pathname,
                counter: 1
              }
            );

            options.headers.authorization = digest.raw;

            return retry(options);
          }
        ],
        beforeRetry: [
          (options, error, retryCount) => {
            console.log(options.headers, error, retryCount);
          }
        ]
      }
    });
  }

```

https://docs.postman-echo.com/
```
const response = await createDigestClient('postman', 'password')('https://postman-echo.com/digest-auth');
  console.log(response.body);

{
  scheme: 'Digest',
  realm: 'Users',
  nonce: 'nKVM5XeTotFSKzoaFX0D9hb6mZvaq6kY',
  qop: 'auth'
}
{
  'user-agent': 'got (https://github.com/sindresorhus/got)',
  authorization: 'Digest username="postman", realm="Users", nonce="nKVM5XeTotFSKzoaFX0D9hb6mZvaq6kY", response="7dc2b8ae3a7e49e7daccc0916dde54b9", cnonce="ae225c6d669f52a2317f01f54bd4bbeece698d2ccaf73f55", nc=00000001, uri="/digest-auth", qop="auth", algorithm="MD5"'
} undefined undefined
{"authenticated":true}
```

```

```

http://httpbin.org/
```
const response = await createDigestClient('test', 'password')('http://httpbin.org/digest-auth/auth/test/password');
 console.log(response.body);

{
  scheme: 'Digest',
  realm: 'me@kennethreitz.com',
  nonce: '3de81da0e604bf1a9b1ffd573c019ddf',
  qop: 'auth',
  opaque: '29c01437151ac325a5e4815237d03aeb',
  stale: 'FALSE',
  algorithm: 'MD5'
}
{
  'user-agent': 'got (https://github.com/sindresorhus/got)',
  authorization: 'Digest username="test", realm="me@kennethreitz.com", nonce="3de81da0e604bf1a9b1ffd573c019ddf", response="2e7ecbe9e441ff5e2913e1beed3d46c1", cnonce="c29174006c6bf716bf28c8ff65ccbe186402bd8851698334", nc=00000001, uri="/digest-auth/auth/test/password",
 qop="auth", algorithm="MD5", opaque="29c01437151ac325a5e4815237d03aeb"'
} undefined undefined
{
  "authenticated": true,
  "user": "test"
}

```

**Comment by vMReal** [comment]
1. About quote, you can do quickly test 

change one row 

```
options.headers.authorization = digest.raw.replace('algorithm="MD5"', 'algorithm=MD5').replace('qop="auth"', 'qop=auth');
```

2. The RPC propose 2 way - with algorithm: 'MD5' and algorithm: 'MD5-sess'

So you can try 

```
 import {ClientDigestAuth, ALGORITHM_MD5_SESS} from '@mreal/digest-auth';

const digest = ClientDigestAuth.generateProtectionAuth(
              incomingDigest,
              username,
              password,
              {
                method: options.method,
                uri: options.url.pathname,
                counter: 1,
                force_algorithm: ALGORITHM_MD5_SESS,
              }
            );
```

**Comment by vMReal** [comment]
According to this information, the algorithm should be with quotes 

https://tools.ietf.org/html/rfc2069#section-2.1.1
https://tools.ietf.org/html/rfc2069#section-2.1.2
```
      domain            = "domain" "=" <"> URI ( 1*SP URI ) <">
      URI               = absoluteURI | abs_path
      nonce             = "nonce" "=" nonce-value
      nonce-value       = quoted-string
      opaque            = "opaque" "=" quoted-string
      stale             = "stale" "=" ( "true" | "false" )
      algorithm         = "algorithm" "=" ( "MD5" | "MD5-sess" |
                           token )
      qop-options       = "qop" "=" <"> 1#qop-value <">
      qop-value         = "auth" | "auth-int" | token

```

**Comment by yovanoc** [comment]
I can't figure it out why it doesn't work on the monero wallet rpc then...thank you

**Comment by raphinesse** [comment]
@vMReal The passage from RFC2069 you posted does specify that the algorithm should be _without_ quotes. The quotes that appear in the grammar just delimit literal tokens. _Literal quotes_ that should appear in the end result are given as `<">` as seen in the rule for `domain` or `qop-options`.

**Comment by vMReal** [comment]
Thanks for such detailed information. It helped me a lot. I am adding fixes asap.

**Comment by raphinesse** [comment]
@vMReal You're welcome. Another word of advice: you should follow above rules for quoting when generating headers, but you should not assume that headers you parse follow them. I played around with a small selection of clients and servers and every one of them violated at least one of those rules.

Maybe [http-header-value](https://www.npmjs.com/package/http-header-value) is worth a look for parsing header values. It's the only library I found that seems to implement a proper parser.

**Comment by vMReal** [comment]
@raphinesse thank you for detailed information and advice

I am pleased to report that all these things already have done.

https://github.com/vMReal/digest-auth/releases/tag/1.1.2

**Comment by vMReal** [comment]
A couple of months ago I tried to replicate this problem with a real environment (**got +  monero-wallet-rpc + digest-auth** and **postman** as addition tools). Unfortunately, I could not find enough time to overcome this problem. But I have **very interesting information**, maybe this can help someone if it's still relevant.

1. I tried to send requests only with **curl**, and it was a success!
2. I tried to send all requests only with the **postman**, and it was a success!
3. I tried to send the first request with the **postman**, then I parse and generate new authorization header with **digest-auth**, then I send the second request with **postman** with using the authorization header from **digest-auth**, and it was a success!

I concluded that the problem persists with the combination **got + monero-wallet-rpc** not related with **digest-auth**

I hope this information helps, I attached all the debug information below

### 2 case

![image](https://user-images.githubusercontent.com/7104203/84703907-a7cadd80-af61-11ea-868e-52c6aed940d1.png)

3 case

parse and generate new header

![image](https://user-images.githubusercontent.com/7104203/84704038-df398a00-af61-11ea-9595-5c26631bc432.png)

`const incomingDigest = ClientDigestAuth.analyze('Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="hiRFOEZB3/Jp8ECzRixg4w==",stale=false');
      const digest = ClientDigestAuth.generateProtectionAuth(
        incomingDigest,
        'testdigest',
        '12345678',
        {
          method: 'POST',
          uri: '/jsonrpc',
          counter: 1
        }
      );
      console.log(digest.raw)`

new header

`Digest username="testdigest", realm="monero-rpc", nonce="hiRFOEZB3/Jp8ECzRixg4w==", response="5f53f30dbd1ca90af1feff04255dab5a", cnonce="ad4bdc2b30dbc37ac799b83e3bc490c0cb7fab7e6448af52", nc=00000001, uri="/jsonrpc", qop=auth, algorithm=MD5`

The second request with this header

![image](https://user-images.githubusercontent.com/7104203/84704156-114aec00-af62-11ea-877f-ced05964e8fd.png)

`POST http://127.0.0.1:18082/json_rpc
401
9ms
POST /json_rpc HTTP/1.1
Content-Type: application/json
User-Agent: PostmanRuntime/7.22.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 994695ff-c14a-4715-b9e8-2aa18d8a6bf1
Host: 127.0.0.1:18082
Accept-Encoding: gzip, deflate, br
Content-Length: 48
Connection: keep-alive
{"jsonrpc":"2.0","id":"0","method":"getbalance"}
HTTP/1.1 401 Unauthorized
Server: Epee-based
Content-Length: 98
Content-Type: text/html
Last-Modified: Sat, 29 Feb 2020 11:47:40 GMT
Accept-Ranges: bytes
WWW-authenticate: Digest qop="auth",algorithm=MD5,realm="monero-rpc",nonce="hiRFOEZB3/Jp8ECzRixg4w==",stale=false
WWW-authenticate: Digest qop="auth",algorithm=MD5-sess,realm="monero-rpc",nonce="hiRFOEZB3/Jp8ECzRixg4w==",stale=false
<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>
 
POST http://127.0.0.1:18082/json_rpc
200
15ms
POST /json_rpc HTTP/1.1
Content-Type: application/json
Authorization: Digest username="testdigest", realm="monero-rpc", nonce="hiRFOEZB3/Jp8ECzRixg4w==", response="5f53f30dbd1ca90af1feff04255dab5a", cnonce="ad4bdc2b30dbc37ac799b83e3bc490c0cb7fab7e6448af52", nc=00000001, uri="/jsonrpc", qop=auth, algorithm=MD5
User-Agent: PostmanRuntime/7.22.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 81c35f0c-be59-4e20-af73-c31a46ae8677
Host: 127.0.0.1:18082
Accept-Encoding: gzip, deflate, br
Content-Length: 48
Connection: keep-alive
{"jsonrpc":"2.0","id":"0","method":"getbalance"}
HTTP/1.1 200 Ok
Server: Epee-based
Content-Length: 171
Content-Type: application/json
Last-Modified: Sat, 29 Feb 2020 11:48:26 GMT
Accept-Ranges: bytes
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "balance": 0,
    "blocks_to_unlock": 0,
    "multisig_import_needed": false,
    "unlocked_balance": 0
  }
}`
